name: Build APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install Android Command Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip
          sudo mkdir -p /usr/local/android-sdk/cmdline-tools
          sudo mv cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
      - name: Accept Android licenses
        run: |
          mkdir -p /usr/local/android-sdk/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > /usr/local/android-sdk/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > /usr/local/android-sdk/licenses/android-sdk-preview-license
      - name: Install required Android SDK packages
        run: |
          yes | sdkmanager --install "platforms;android-30" "build-tools;30.0.3" "platform-tools" --sdk_root=${ANDROID_HOME}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install cython buildozer
      - name: Install additional build dependencies
        run: |
          sudo apt-get install -y \
            libssl-dev \
            libffi-dev \
            build-essential \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev
      - name: Update buildozer.spec
        run: |
          sed -i 's/^android.sdk_path =.*/android.sdk_path = \/usr\/local\/android-sdk/' buildozer.spec
          sed -i 's/^android.accept_sdk_license =.*/android.accept_sdk_license = True/' buildozer.spec
          sed -i 's/^android.build_tools =.*/android.build_tools = 30.0.3/' buildozer.spec
      - name: Build APK
        run: |
          yes | buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: todo_app_apk
          path: bin/*.apk
