name: Build APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install Android Command Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip
          sudo mkdir -p /usr/local/android-sdk/cmdline-tools
          sudo mv cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses
      - name: Install required Android SDK packages
        run: |
          sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer
      - name: Build APK
        run: |
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: todo_app_apk
          path: bin/*.apk
