name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade pip
          pip3 install buildozer

      - name: Build APK
        run: |
          buildozer -v android debug  # Build the APK in debug mode

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: todo_app_apk
          path: bin/*.apk  # Adjust this if your APK is located elsewhere
